language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - 'nightly'
os: linux
## only syntax check. there is no real test suite for pcc.
script: php phpconfigcheck.php
